
# docker-compose up -d
version: '3' # version của docker-compose
 # định nghĩa đóng gói image và khởi tạo container cho các source
services:
  api_gateway:
    container_name: api_gateway
    build: ./api_gateway 
    # image: hintran/nodeadv03
    ports:
      - 8080:8080
    networks:
      - node-network

  service_notify:
    container_name: service_notify
    build: ./service_notify 
    networks:
      - node-network
  
  service_order:
    container_name: service_order
    build: ./service_order 
    networks:
      - node-network
  
  service_product:
    container_name: service_product
    build: ./service_product 
    networks:
      - node-network

  service_shipping:
    container_name: service_shipping
    build: ./service_shipping 
    networks:
      - node-network

  
networks:
  node-network:
    external: true # sử dụng network đã tạo sẵn
      
  